name: homelabos

services:
  api:
    build: ./backend
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
      - /home/arsani:/home/arsani
    environment:
      STORAGE_PATH: /home/arsani
    pid: host
    networks: [homelabos]
  web:
    build: ./frontend
    restart: unless-stopped
    depends_on: [api]
    ports:
      - "${HOMELABOS_PORT:-8080}:80"
    networks: [homelabos]
  ttyd:
    build: ./terminal
    restart: unless-stopped
    command: ["ttyd", "-W", "-b", "/ttyd", "nsenter", "-t", "1", "-m", "-u", "-i", "-n", "-p", "sh", "-c", "cd /root && exec bash --login"]
    privileged: true
    pid: host
    networks: [homelabos]
networks:
  homelabos:
    driver: bridge
